/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "ingest.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(aetus_ingest_v1_IngestEvent, aetus_ingest_v1_IngestEvent, 2)


PB_BIND(aetus_ingest_v1_TelemetryPayload, aetus_ingest_v1_TelemetryPayload, 2)


PB_BIND(aetus_ingest_v1_MetricSet, aetus_ingest_v1_MetricSet, 2)


PB_BIND(aetus_ingest_v1_Metric, aetus_ingest_v1_Metric, AUTO)


PB_BIND(aetus_ingest_v1_StatusPayload, aetus_ingest_v1_StatusPayload, AUTO)


PB_BIND(aetus_ingest_v1_AlertPayload, aetus_ingest_v1_AlertPayload, AUTO)


PB_BIND(aetus_ingest_v1_SignalFrame, aetus_ingest_v1_SignalFrame, AUTO)


PB_BIND(aetus_ingest_v1_SignalChannel, aetus_ingest_v1_SignalChannel, AUTO)













#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

